language: ruby
rvm:
 - 1.9.3
before_install:
 - gem build miiCardConsumers.gemspec
 - find . -maxdepth 1 -iname "*.gem" -print0 | xargs -0 gem install
script:
 - ruby test/test_miiCardConsumers.rb
notifications:
  email: false